/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummerCampRouteImport } from './routes/summer-camp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CampsVacancesRouteImport } from './routes/camps-vacances'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminChoiceRouteImport } from './routes/admin-choice'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitesRouteImport } from './routes/activites'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmSettingsRouteImport } from './routes/crm.settings'
import { Route as CrmPaymentsRouteImport } from './routes/crm.payments'
import { Route as CrmDashboardRouteImport } from './routes/crm.dashboard'
import { Route as CrmCustomersRouteImport } from './routes/crm.customers'
import { Route as CrmCampsRouteImport } from './routes/crm.camps'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as CrmCustomersIdRouteImport } from './routes/crm.customers.$id'

const SummerCampRoute = SummerCampRouteImport.update({
  id: '/summer-camp',
  path: '/summer-camp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CampsVacancesRoute = CampsVacancesRouteImport.update({
  id: '/camps-vacances',
  path: '/camps-vacances',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChoiceRoute = AdminChoiceRouteImport.update({
  id: '/admin-choice',
  path: '/admin-choice',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitesRoute = ActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmSettingsRoute = CrmSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPaymentsRoute = CrmPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => CrmRoute,
} as any)
const CrmDashboardRoute = CrmDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCustomersRoute = CrmCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCampsRoute = CrmCampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => CrmRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const CrmCustomersIdRoute = CrmCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CrmCustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-choice': typeof AdminChoiceRoute
  '/blog': typeof BlogRoute
  '/boutique': typeof BoutiqueRoute
  '/camps-vacances': typeof CampsVacancesRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/login': typeof LoginRoute
  '/summer-camp': typeof SummerCampRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/crm/camps': typeof CrmCampsRoute
  '/crm/customers': typeof CrmCustomersRouteWithChildren
  '/crm/dashboard': typeof CrmDashboardRoute
  '/crm/payments': typeof CrmPaymentsRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/customers/$id': typeof CrmCustomersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-choice': typeof AdminChoiceRoute
  '/blog': typeof BlogRoute
  '/boutique': typeof BoutiqueRoute
  '/camps-vacances': typeof CampsVacancesRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/login': typeof LoginRoute
  '/summer-camp': typeof SummerCampRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/crm/camps': typeof CrmCampsRoute
  '/crm/customers': typeof CrmCustomersRouteWithChildren
  '/crm/dashboard': typeof CrmDashboardRoute
  '/crm/payments': typeof CrmPaymentsRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/customers/$id': typeof CrmCustomersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-choice': typeof AdminChoiceRoute
  '/blog': typeof BlogRoute
  '/boutique': typeof BoutiqueRoute
  '/camps-vacances': typeof CampsVacancesRoute
  '/contact': typeof ContactRoute
  '/crm': typeof CrmRouteWithChildren
  '/login': typeof LoginRoute
  '/summer-camp': typeof SummerCampRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/crm/camps': typeof CrmCampsRoute
  '/crm/customers': typeof CrmCustomersRouteWithChildren
  '/crm/dashboard': typeof CrmDashboardRoute
  '/crm/payments': typeof CrmPaymentsRoute
  '/crm/settings': typeof CrmSettingsRoute
  '/crm/customers/$id': typeof CrmCustomersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/activites'
    | '/admin'
    | '/admin-choice'
    | '/blog'
    | '/boutique'
    | '/camps-vacances'
    | '/contact'
    | '/crm'
    | '/login'
    | '/summer-camp'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/submissions'
    | '/crm/camps'
    | '/crm/customers'
    | '/crm/dashboard'
    | '/crm/payments'
    | '/crm/settings'
    | '/crm/customers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/activites'
    | '/admin'
    | '/admin-choice'
    | '/blog'
    | '/boutique'
    | '/camps-vacances'
    | '/contact'
    | '/crm'
    | '/login'
    | '/summer-camp'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/submissions'
    | '/crm/camps'
    | '/crm/customers'
    | '/crm/dashboard'
    | '/crm/payments'
    | '/crm/settings'
    | '/crm/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/activites'
    | '/admin'
    | '/admin-choice'
    | '/blog'
    | '/boutique'
    | '/camps-vacances'
    | '/contact'
    | '/crm'
    | '/login'
    | '/summer-camp'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/submissions'
    | '/crm/camps'
    | '/crm/customers'
    | '/crm/dashboard'
    | '/crm/payments'
    | '/crm/settings'
    | '/crm/customers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ActivitesRoute: typeof ActivitesRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminChoiceRoute: typeof AdminChoiceRoute
  BlogRoute: typeof BlogRoute
  BoutiqueRoute: typeof BoutiqueRoute
  CampsVacancesRoute: typeof CampsVacancesRoute
  ContactRoute: typeof ContactRoute
  CrmRoute: typeof CrmRouteWithChildren
  LoginRoute: typeof LoginRoute
  SummerCampRoute: typeof SummerCampRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summer-camp': {
      id: '/summer-camp'
      path: '/summer-camp'
      fullPath: '/summer-camp'
      preLoaderRoute: typeof SummerCampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camps-vacances': {
      id: '/camps-vacances'
      path: '/camps-vacances'
      fullPath: '/camps-vacances'
      preLoaderRoute: typeof CampsVacancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-choice': {
      id: '/admin-choice'
      path: '/admin-choice'
      fullPath: '/admin-choice'
      preLoaderRoute: typeof AdminChoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activites': {
      id: '/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof ActivitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/settings': {
      id: '/crm/settings'
      path: '/settings'
      fullPath: '/crm/settings'
      preLoaderRoute: typeof CrmSettingsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/payments': {
      id: '/crm/payments'
      path: '/payments'
      fullPath: '/crm/payments'
      preLoaderRoute: typeof CrmPaymentsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/dashboard': {
      id: '/crm/dashboard'
      path: '/dashboard'
      fullPath: '/crm/dashboard'
      preLoaderRoute: typeof CrmDashboardRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/customers': {
      id: '/crm/customers'
      path: '/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof CrmCustomersRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/camps': {
      id: '/crm/camps'
      path: '/camps'
      fullPath: '/crm/camps'
      preLoaderRoute: typeof CrmCampsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/crm/customers/$id': {
      id: '/crm/customers/$id'
      path: '/$id'
      fullPath: '/crm/customers/$id'
      preLoaderRoute: typeof CrmCustomersIdRouteImport
      parentRoute: typeof CrmCustomersRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CrmCustomersRouteChildren {
  CrmCustomersIdRoute: typeof CrmCustomersIdRoute
}

const CrmCustomersRouteChildren: CrmCustomersRouteChildren = {
  CrmCustomersIdRoute: CrmCustomersIdRoute,
}

const CrmCustomersRouteWithChildren = CrmCustomersRoute._addFileChildren(
  CrmCustomersRouteChildren,
)

interface CrmRouteChildren {
  CrmCampsRoute: typeof CrmCampsRoute
  CrmCustomersRoute: typeof CrmCustomersRouteWithChildren
  CrmDashboardRoute: typeof CrmDashboardRoute
  CrmPaymentsRoute: typeof CrmPaymentsRoute
  CrmSettingsRoute: typeof CrmSettingsRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmCampsRoute: CrmCampsRoute,
  CrmCustomersRoute: CrmCustomersRouteWithChildren,
  CrmDashboardRoute: CrmDashboardRoute,
  CrmPaymentsRoute: CrmPaymentsRoute,
  CrmSettingsRoute: CrmSettingsRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ActivitesRoute: ActivitesRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminChoiceRoute: AdminChoiceRoute,
  BlogRoute: BlogRoute,
  BoutiqueRoute: BoutiqueRoute,
  CampsVacancesRoute: CampsVacancesRoute,
  ContactRoute: ContactRoute,
  CrmRoute: CrmRouteWithChildren,
  LoginRoute: LoginRoute,
  SummerCampRoute: SummerCampRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
